### ISSUE TITLE
How to use RCNN layer for speech in general

### ISSUE THREAD

**Issue by pj1527** [zhaoyue-zephyrus/RecurrentConvNet-for-Speech#1]
I have gone through the paper where you introduced RCNN layer for emotion classification and ASR, I would like to use is for a speech classification task of my own. Can you guide me to library or something like that from where I can find an implementation of this layer?

**Comment by zhaoyue-zephyrus** [comment]
Hi @pj1527 ,

Thanks for your interests in our work. 

1. The required libraries include Kaldi and CNTK (You can find more in the [README](https://github.com/zhaoyue-zephyrus/RecurrentConvNet-for-Speech/blob/master/README.md))
2. To have a quick peek at the structure, you may find [the config](https://github.com/zhaoyue-zephyrus/RecurrentConvNet-for-Speech/blob/master/timit-scripts/cntk_config/rcnn_tri0.ndl#L105) helpful. It won't be that difficult to implement with some more popular framework such as PyTorch.

**Comment by pj1527** [comment]
Thanks
